- name: Project
  hosts: localhost
  become: false
  gather_facts: false

  vars:
    file_and_cont:
      - name: "file_a"
        content: "Hi this is content of file_a"
      - name: "file_b"
        content: "Hi this is content of file_b"
      - name: "file_c"
        content: "Hi this is content of file_c"
      - name: "file_d"
        content: "Hi this is content of file_d"

    deploy_enabled: false

  tasks:
    - block:
        - name: "INSTALL | Install package A"
          debug:
            msg: "Installing package A"

        - name: "INSTALL | Install package B"
          debug:
            msg: "Installing package B"
      tags:
        - install

    - block:
        - name: "CONFIGURE | Load configure tasks"
          include_tasks: tasks/configure_tasks.yml
      tags:
        - configure

    - name: Flush handlers after configure
      meta: flush_handlers
      

    - block:
        - name: "DEPLOY | Deploy package"
          debug:
            msg: "Deploying package from files"

        - name: "DEPLOY | Health check"
          command: test -f /tmp/file_a
          register: health_check
          until: health_check.rc == 0
          retries: 3
          delay: 5
      tags:
        - deploy

      rescue:
        - name: Printing the task name that got failed
          debug:
            msg: "Failed task name: {{ ansible_failed_task.name }}"
      always:
        - name: Run Always
          debug:
            msg: "Deploy Attempt Finished"
      when: deploy_enabled == true

    - name: Stretch Goal 1 - Print all variables
      debug:
        msg:
          - "Name is {{ item.name }} and Content is {{ item.content }}"
          - "deploy_enabled is {{ deploy_enabled }}"
      loop: "{{ file_and_cont }}"
      tags:
        - never
        - debug

  handlers:
    - name: Restart Service
      debug:
        msg: "Restart App Service"

## Commands
# ansible-playbook project_app_setup.yml --tags install
# ansible-playbook project_app_setup.yml --tags configure
# ansible-playbook project_app_setup.yml --tags deploy
# ansible-playbook project_app_setup.yml --tags deploy -e "deploy_enabled=true"