- name: Deploy webserver
  hosts: localhost
  vars:
    http_port: 8080
    nginx_user: "myuser"
  roles:
    - webserver
    - common # Exercise 3, it will run twice as its defined here and allow_duplcates: true