- name: "CONFIGURE | Configure service A"
  debug:
    msg: "Configuring service A"
  tags:
    - configure
    
- name: "CONFIGURE | Configure service B"
  debug:
    msg: "Configuring service B"
  tags:
    - configure