- name: "INSTALL | Install package A"
  debug:
    msg: "Installing package A"
  tags:
    - install

- name: "INSTALL | Install package B"
  debug:
    msg: "Installing package B"
  tags:
    - install