all:
  vars:
    ansible_user: ubuntu
    ansible_port: 22

  children:
    webservers:
      hosts:
        web01.com:
          ansible_host: 52.3.230.254

    databases:
      hosts:
        db01.com: