all:
  vars:
    ansible_user: ubuntu
    ansible_port: 22
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/ansible_managed_node.pem

  children:
    webservers:
      hosts:
        web01:
          ansible_host: ${managed_one_ip}

    databases:
      hosts:
        db01:
          ansible_host: ${managed_one_ip}

