all:
  vars:
    ansible_user: ubuntu
    ansible_port: 22

  children:
    webservers:
      hosts:
        web01.com:
          ansible_host: 13.223.73.208
        db01.com:
          ansible_host: 54.172.87.184

    databases:
      hosts:
        db01.com: