plugin: ansible.builtin.constructed
sources: 
  - ../static/inventory.yml

groups:
  production: env == "prod"
  staging: env == "staging"
  web_tier: role == "web"
  db_tier: role == "db"

keyed_groups:
  - prefix: env
    key: env
  - prefix: role
    key: role
compose:
  environment_label: env + '-' + role

# ansible-inventory -i inventory/dynamic/constructed.yml --graph
# ansible-inventory -i inventory/dynamic/constructed.yml --list

