- name: Variable sources — where can variables be defined?
  hosts: all
  become: true
  gather_facts: true
  vars:

  tasks:
    - name: Print Web variables
      debug:
        msg: "Web Port={{ web_port }}"
      when: web_port is defined

    - name: Print DB variabled
      debug:
        msg: "DB Port={{ db_port }}"
      when: db_port is defined

# ansible-playbook -i inventory.yml 01_variable_source.yml --check
