- name: Tutorial About Jinja2 syntax and its filters
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: "Use of default if a variable is undefined"
      debug:
        msg: "Undefined Variable is {{ undef_var | default('not set') }}"

    - name: "Print only server names as list"
      debug:
        msg: "{{ servers | map(attribute='name') }}"

    - name: "Print only server names as comma separated in a single string => 'a,b,c'"
      debug:
        msg: "{{ servers | map(attribute='name') | join(', ') }}"
    
    - name: "Print all attributes of server, where role = web"
      debug:
        msg: "{{ servers | selectattr('role','equalto','web') }}"
    
    - name: "Print only name attribute of server, where role = web"
      debug:
        msg: "{{ servers | selectattr('role','equalto','web') | map(attribute='name') }}"

    