- name: This playbook will render a jinja2 template on localhost
  hosts: localhost # implicit localhost added not in mini_project or any other 
  become: true
  gather_facts: true
  vars_files:
    - vars/app_vars.yml
  tasks:
    - name: Rendering the template with variables
      template:
        src: templates/app_config.j2
        dest: /tmp/app_config.conf

# Run it with

# ansible-playbook -i inventory/inventory.yml 06_templates.yml
## Runs on localhost only (hosts: localhost), loads vars/app_vars.yml (vars_files) AND group_vars/all.yml from inventory dir
## vars_files has higher precedence than group_vars, so app_vars.yml wins on conflicts

# ansible-playbook 06_templates.yml
## Uses implicit localhost, loads only vars/app_vars.yml (no inventory dir = no group_vars loaded)