- name: This playbook will render a jinja2 template on localhost
  hosts: localhost
  become: true
  gather_facts: true
  vars:
    app_name: localhost_app
  tasks:
    - name: Rendering the template with variables
      template:
        src: templates/app_config.j2
        dest: /tmp/app_config.conf