- name: Check Variables defined and undefined output
  hosts: all
  become: true
  gather_facts: true
  vars:
    # my_var: large
  tasks:
    - name: Print with default - safe fallback
      debug:
        msg: "{{ undef_var | default('fallback value') }}"
    
    - name: Skip when undefined - only runs if my_var is defined
      debug:
        msg: "{{ undef_var | default('fallback value') }}"
      when: my_var is defined # works only if defined, try comment & uncomment the variable