- name: Playbook that generates a system report file for each host
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - vars/app_vars.yml
  vars_prompt:
    - name: operator_name
      prompt: "Enter operator name"
      private: false # show input as typed — not a secret
  tasks:
    - name: Creating System report
      template:
        src: templates/system_report.j2
        dest: /tmp/system_report_{{ inventory_hostname }}.txt
      when: ansible_facts['memtotal_mb'] > 900
      register: report_result       # <-- save the task's return value here

    - name: Report generated
      debug:
        msg: "Report created for {{ inventory_hostname }} | RAM: {{ ansible_facts['memtotal_mb'] }} MB | OS: {{ ansible_facts['os_family'] }}"
      when: ansible_facts['memtotal_mb'] > 900

    - name: Report not generated
      debug:
        msg: "Report not Generated as total memory is {{ ansible_facts['memtotal_mb'] }} which is < 900 MB"
      when: ansible_facts['memtotal_mb'] < 900

    - name: Report status
      debug:
        msg: "{{ 'File CHANGED' if report_result.changed else 'Already up to date' }}"
      when: ansible_facts['memtotal_mb'] > 900

## Command to run on localhost
# ansible-playbook -i "localhost," mini_project.yml -e "ansible_connection=local"
## Command to run on inventory hosts
# ansible-playbook -i inventory/inventory.yml mini_project.yml