- name: Testing Construcuted plugin
  hosts: all
  gather_facts: false
  tasks:
    - name: Print Hostnames
      debug:
        msg: "Hostname : {{ inventory_hostname }}"
    - name: Print Group Names
      debug:
        msg: "Group Names : {{ group_names }}"
    - name: Print environment_label
      debug:
        msg: "Environment Label : {{ environment_label }}"

# ansible-playbook -i inventory/static/inventory.yml -i inventory/combined/ 03_performance_tuning.yml